name: Build and Push Docker Image to ghcr.io

on:
  push:
    tags:
      - '*'  # Löst den Workflow bei jedem Tag aus

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set lowercase username
        id: lowercase_username
        run: |
          echo "actor=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: '${{ github.repository_owner }}'
        shell: bash

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lowercase_username.outputs.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ steps.lowercase_username.outputs.actor }}/${{ github.event.repository.name }}/flask-app:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ steps.lowercase_username.outputs.actor }}/${{ github.event.repository.name }}/flask-app:latest
